### ISSUE TITLE
出现bug

### ISSUE THREAD

**Issue by Deniffer** [fgksgf/DCVS#3]
根据requirements.txt 配置好环境之后，我是在centos7下操作的，但环境没配错，直接 pip install requirements .txt的，报错是找不到service.py 的page 具体如下
ImportError: cannot import name 'Page' from 'pyecharts' (/root/env/lib/python3.7/site-packages/pyecharts/__init__.py)

**Comment by fgksgf** [comment]
因为pyecharts这个库进行了重构，许多方法发生了改变，你可以将`requirements.txt`中的依赖修改为[初始版本](https://github.com/fgksgf/DCVS/commit/0dfdd674b623f17b1d041d0ec5a67a48ce20c624#diff-b4ef698db8ca845e5845c4618278f29a)来运行，或者等待相关代码更新。

**Comment by Deniffer** [comment]
@fgksgf 出现了验证码无法加载图片的情景 请问这个怎么解决呢？

**Comment by fgksgf** [comment]
@Deniffer 代码已更新，删除了验证码功能，更新了可视化功能的函数，使其兼容v1.0版的[pyecharts](https://github.com/pyecharts/pyecharts)库，文档仍在更新中
